server:
  port: 9090

spring:
  application:
    name: wecom

logging:
  config: classpath:logback-spring.xml

apollo:
  bootstrap:
    enabled : true
    namespaces: application,
      XYZ.redis_sentinel,
      XYZ.redis_low_rel,
      XYZ.weCom
